language: python

python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pylint
# command to run tests
script:
  - python3 -m unittest tests/test_thanosdb.py -v
  - python run_pylint.py --disable=fixme --fail-under=8 thanosdb/
